[package]
name = 'Vault'
version = '1.0.0'


[dependencies.AptosFramework]
git = 'https://github.com/davidiw/aptos-core.git'
rev = 'main'
subdir = 'aptos-move/framework/aptos-framework'


[addresses]
vault = "0x2f6332621ecc6915b29b51958ae598ce4eea2cb4a2085162c1160a3b3897ddb7"
